version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=pesu@123
      - MYSQL_DATABASE=contractor_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/models/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: